apiVersion: v1
kind: Service
metadata:
  name: java-frontend-service
spec:
  selector:
    type: java-frontend
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      type: java-frontend
  template:
    metadata:
      labels:
        type: java-frontend
    spec:
      containers:
      - name: java-frontend-container
        image: did09/javacode
        ports:
        - containerPort: 5000